export default [
  {
    ignores: [
      'node_modules/',
      'secura-report.json',
      'test-project/',
    ],
  },
  {
    languageOptions: {
      globals: {
        console: 'readonly',
        process: 'readonly',
        Buffer: 'readonly',
        setTimeout: 'readonly',
        setInterval: 'readonly',
        clearInterval: 'readonly',
        clearTimeout: 'readonly',
        fetch: 'readonly',
        require: 'readonly',
        module: 'readonly',
        exports: 'readonly',
        __dirname: 'readonly',
        __filename: 'readonly',
        global: 'readonly',
        setImmediate: 'readonly',
        clearImmediate: 'readonly',
        spawn: 'readonly',
        createInterface: 'readonly',
        readFileSync: 'readonly',
        writeFileSync: 'readonly',
        existsSync: 'readonly',
        readdirSync: 'readonly',
        statSync: 'readonly',
        readFile: 'readonly',
        writeFile: 'readonly',
        readlinkSync: 'readonly',
        mkdirSync: 'readonly',
        unlinkSync: 'readonly',
        rmdirSync: 'readonly',
        renameSync: 'readonly',
        copyFileSync: 'readonly',
        appendFileSync: 'readonly',
        lstatSync: 'readonly',
        watch: 'readonly',
        unwatch: 'readonly',
      },
    },
    rules: {
      'no-unused-vars': 'warn',
      'prefer-const': 'warn',
      'no-var': 'error',
    },
  },
];